spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    # MySQL 설정
    url: jdbc:mysql://{hostname}?useSSL=false&serverTimezone=Asia/Seoul
    username: { 계정명 }
    password: { 비밀번호 }
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql=true:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력